Source/RavenDB_Embedded/Models/QuanLy.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RavenDB_Embedded.Models
{
    public class QuanLy
    {
        public string MaQL { get; set; }
        public string TenQL { get; set; }
        public string SoDienThoai { get; set; }
    }
}

Source/RavenDB_Embedded/Controllers/QuanLyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Raven.Client.Documents.Session;
using RavenDB_Embedded.Models;

namespace RavenDB_Embedded.Controllers
{
    public class QuanLyController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult ListYeuCau()
        {
            List<YeuCauMuaSach> li = RavenDBHelper.LoadListYC();
            return View(li);
        }
        public IActionResult ListPhanBo()
        {
            List<PhanBoSach> pb = RavenDBHelper.ListPhanBoSach();
            return View(pb);
        }
        //Delete yêu cầu (sau khi xem)
        public IActionResult DeleteYC(string id)
        {
            id = id.Replace("*", "/");
            var store = RavenDBHelper.store.Initialize();
            YeuCauMuaSach ms = new YeuCauMuaSach();
            using (IDocumentSession session = store.OpenSession())
            {
                ms = session.Load<YeuCauMuaSach>(id);
                session.Delete<YeuCauMuaSach>(ms);
                session.SaveChanges();
            }
            return RedirectToAction("ListYeuCau");
        }

        //CRUD phân bố sách
        public IActionResult CreatePBSach()
        {
            return View();
        }
        [HttpPost]
        public IActionResult CreatePBSach(PhanBoSach pbs)
        {
            var store = RavenDBHelper.store.Initialize();
            if (!ModelState.IsValid)
                return View();
            using (IDocumentSession session = store.OpenSession())
            {
                if (pbs.KiemTra == true)
                {
                    session.Store(pbs);
                    session.SaveChanges();
                }
            }
            return RedirectToAction("ListPhanBo");
        }

        public IActionResult EditPBSach(string id)
        {
            var store = RavenDBHelper.store.Initialize();
            using (IDocumentSession session = store.OpenSession())
            {
                id = id.Replace("*","/");
                var pbs = session.Load<PhanBoSach>(id);
                if (pbs == null)
                    return RedirectToAction("ListPhanBo");
                pbs.Id = pbs.Id.Replace("*","/");
                return View(pbs);
            }
        }

        [HttpPost]
        public IActionResult EditPBSach(PhanBoSach pbs)
        {
            if (pbs.Id.Contains("*"))
                pbs.Id.Replace("*","/");
            var store = RavenDBHelper.store.Initialize();
            if (!ModelState.IsValid)
                return View();
            using (IDocumentSession session = store.OpenSession())
            {
                if (pbs.KiemTra == true)
                {                    
                    session.Store(pbs);
                    session.SaveChanges();                    
                }
            }
            return RedirectToAction("ListPhanBo");
        }

        [ActionName("DeletePBSach")]

        public IActionResult DeletePBSach(string id)
        {
            var store = RavenDBHelper.store.Initialize();
            PhanBoSach pb = new PhanBoSach();
            using (IDocumentSession session = store.OpenSession())
            {
                id = id.Replace("*","/");
                pb = session.Load<PhanBoSach>(id);
                session.Delete<PhanBoSach>(pb);
                session.SaveChanges();
            }
            return RedirectToAction("ListPhanBo");
        }

        public IActionResult ListSach()
        {
            return View(RavenDBHelper.ListSach());
        }


        //CRUD Quản lý sách
        public IActionResult AddSach()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddSach(Sach s)
        {
            var store = RavenDBHelper.store.Initialize();
            if (!ModelState.IsValid)
                return View();
            using (IDocumentSession session = store.OpenSession())
            {
                session.Store(s);
                session.SaveChanges();
            }
            return RedirectToAction("ListSach");            
        }

        public IActionResult EditSach(string id)
        {
            var store = RavenDBHelper.store.Initialize();
            using (IDocumentSession session = store.OpenSession())
            {
                id = id.Replace("*", "/");
                var s = session.Load<Sach>(id);
                if (s == null)
                    return RedirectToAction("ListSach");
                return View(s);
            }            
        }
        [HttpPost]
        public IActionResult EditSach(Sach s)
        {
            if (s.Id.Contains("*"))
                s.Id.Replace("*", "/");
            var store = RavenDBHelper.store.Initialize();
            if (!ModelState.IsValid)
                return View();
            using (IDocumentSession session = store.OpenSession())
            {
                session.Store(s);
                session.SaveChanges();
            }
            return RedirectToAction("ListSach");
        }
        [ActionName("DeleteSach")]
        public IActionResult DeleteSach(string id)
        {
            var store = RavenDBHelper.store.Initialize();
            Sach s = new Sach();
            using (IDocumentSession session = store.OpenSession())
            {
                id = id.Replace("*", "/");
                s = session.Load<Sach>(id);
                session.Delete<Sach>(s);
                session.SaveChanges();
            }
            return RedirectToAction("ListSach");            
        }

        //CRUD Quản lý độc giả
        public IActionResult ListDocGia()
        {
            List<DocGia> dg = RavenDBHelper.ListDocGia(null,null);
            return View(dg);
        }
        public IActionResult AddDocGia()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddDocGia(DocGia dg)
        {
            var store = RavenDBHelper.store.Initialize();
            if (!ModelState.IsValid)
                return View();
            using (IDocumentSession session = store.OpenSession())
            {
                if (dg.MaLoaiDG == "GV")
                {
                    DocGiaGV gv = new DocGiaGV();
                    gv.CastToGV(dg);
                    session.Store(gv);
                }
                else if (dg.MaLoaiDG == "SV")
                {
                    DocGiaSV sv = new DocGiaSV();
                    sv.CastToSV(dg);
                    session.Store(sv);
                }
                else if (dg.MaLoaiDG == "T")
                {
                    DocGiaThuong t = new DocGiaThuong();
                    t.CastToThuong(dg);
                    session.Store(t);
                }
                session.SaveChanges();
            }
            return RedirectToAction("ListDocGia");
        }

        public IActionResult EditDocGia(string id)
        {
            var store = RavenDBHelper.store.Initialize();
            using (IDocumentSession session = store.OpenSession())
            {
                id = id.Replace("*", "/");                               
                var dg = session.Load<DocGia>(id);                
                if (dg == null)
                    return RedirectToAction("ListDocGia");
                return View(dg);
            }
        }
        [HttpPost]
        public IActionResult EditDocGia(DocGia dg)
        {
            if (dg.Id.Contains("*"))
                dg.Id.Replace("*", "/");
            var store = RavenDBHelper.store.Initialize();
            if (!ModelState.IsValid)
                return View();
            using (IDocumentSession session = store.OpenSession())
            {
                if (dg.MaLoaiDG == "GV")
                {
                    DocGiaGV gv = new DocGiaGV();
                    gv.CastToGV(dg);
                    session.Store(gv);
                }
                else if (dg.MaLoaiDG == "SV")
                {
                    DocGiaSV sv = new DocGiaSV();
                    sv.CastToSV(dg);
                    session.Store(sv);
                }
                else if (dg.MaLoaiDG == "T")
                {
                    DocGiaThuong t = new DocGiaThuong();
                    t.CastToThuong(dg);
                    session.Store(t);
                }
                session.SaveChanges();
            }
            return RedirectToAction("ListDocGia");
        }
        [ActionName("DeleteDocGia")]
        public IActionResult DeleteDocGia(string id)
        {
            var store = RavenDBHelper.store.Initialize();            
            using (IDocumentSession session = store.OpenSession())
            {
                id = id.Replace("*", "/");
                DocGia dg = session.Query<DocGia, DocGias_ByMaDG>().Where(x=>x.Id == id).SingleOrDefault();
                if (dg.MaLoaiDG == "GV") {
                    var tmp = session.Load<DocGiaGV>(dg.Id);
                    session.Delete<DocGiaGV>(tmp);
                }
                else if (dg.MaLoaiDG == "SV")
                {
                    var tmp = session.Load<DocGiaSV>(dg.Id);
                    session.Delete<DocGiaSV>(tmp);
                }
                else if (dg.MaLoaiDG == "T")
                {                    
                    var tmp = session.Load<DocGiaThuong>(dg.Id);
                    session.Delete<DocGiaThuong>(tmp);
                }
                session.SaveChanges();
            }
            return RedirectToAction("ListDocGia");
        }
    }
}

Source/RavenDB_Embedded/Views/QuanLy/AddDocGia.cshtml
@model RavenDB_Embedded.Models.DocGia

@{
    ViewData["Title"] = "AddDocGia";
}

<h2>AddDocGia</h2>

<h4>DocGia</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddDocGia">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MaLoaiDG" class="control-label"></label>
                <input asp-for="MaLoaiDG" class="form-control" />
                <span asp-validation-for="MaLoaiDG" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MaDG" class="control-label"></label>
                <input asp-for="MaDG" class="form-control" />
                <span asp-validation-for="MaDG" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TenDG" class="control-label"></label>
                <input asp-for="TenDG" class="form-control" />
                <span asp-validation-for="TenDG" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SoDienThoai" class="control-label"></label>
                <input asp-for="SoDienThoai" class="form-control" />
                <span asp-validation-for="SoDienThoai" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Source/RavenDB_Embedded/Views/QuanLy/AddSach.cshtml
@model RavenDB_Embedded.Models.Sach

@{
    ViewData["Title"] = "AddSach";
}

<h2>AddSach</h2>

<h4>Sach</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddSach">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MaSach" class="control-label"></label>
                <input asp-for="MaSach" class="form-control" />
                <span asp-validation-for="MaSach" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TenSach" class="control-label"></label>
                <input asp-for="TenSach" class="form-control" />
                <span asp-validation-for="TenSach" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Hinh" class="control-label"></label>
                <input asp-for="Hinh" class="form-control" />
                <span asp-validation-for="Hinh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TenTacGia" class="control-label"></label>
                <input asp-for="TenTacGia" class="form-control" />
                <span asp-validation-for="TenTacGia" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NhaXuatBan" class="control-label"></label>
                <input asp-for="NhaXuatBan" class="form-control" />
                <span asp-validation-for="NhaXuatBan" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NamXuatBan" class="control-label"></label>
                <input asp-for="NamXuatBan" class="form-control" />
                <span asp-validation-for="NamXuatBan" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LoiGioiThieu" class="control-label"></label>
                <input asp-for="LoiGioiThieu" class="form-control" />
                <span asp-validation-for="LoiGioiThieu" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rating" class="control-label"></label>
                <input asp-for="Rating" class="form-control" />
                <span asp-validation-for="Rating" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ChiNhanh" class="control-label"></label>
                <input asp-for="ChiNhanh" class="form-control" />
                <span asp-validation-for="ChiNhanh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Source/RavenDB_Embedded/Views/QuanLy/CreatePBSach.cshtml
@model RavenDB_Embedded.Models.PhanBoSach

@{
    ViewData["Title"] = "CreatePBSach";
}

<h2>CreatePBSach</h2>

<h4>PhanBoSach</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreatePBSach">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group" hidden>
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MaSach" class="control-label"></label>
                <input asp-for="MaSach" class="form-control" />
                <span asp-validation-for="MaSach" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MaChiNhanh" class="control-label"></label>
                <input asp-for="MaChiNhanh" class="form-control" />
                <span asp-validation-for="MaChiNhanh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SoLuongGoc" class="control-label"></label>
                <input asp-for="SoLuongGoc" class="form-control" />
                <span asp-validation-for="SoLuongGoc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SoLuongCon" class="control-label"></label>
                <input asp-for="SoLuongCon" class="form-control" />
                <span asp-validation-for="SoLuongCon" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="KiemTra" /> @Html.DisplayNameFor(model => model.KiemTra)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Source/RavenDB_Embedded/Views/QuanLy/EditDocGia.cshtml
@model RavenDB_Embedded.Models.DocGia

@{
    ViewData["Title"] = "EditDocGia";
}

<h2>EditDocGia</h2>

<h4>DocGia</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditDocGia">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" value="@{if (Model.Id.Contains("*")) { Model.Id.Replace("*", "/"); } else { @Model.Id; }}"/>
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MaLoaiDG" class="control-label"></label>
                <input asp-for="MaLoaiDG" class="form-control" />
                <span asp-validation-for="MaLoaiDG" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MaDG" class="control-label"></label>
                <input asp-for="MaDG" class="form-control" />
                <span asp-validation-for="MaDG" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TenDG" class="control-label"></label>
                <input asp-for="TenDG" class="form-control" />
                <span asp-validation-for="TenDG" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SoDienThoai" class="control-label"></label>
                <input asp-for="SoDienThoai" class="form-control" />
                <span asp-validation-for="SoDienThoai" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Source/RavenDB_Embedded/Views/QuanLy/EditPBSach.cshtml
@model RavenDB_Embedded.Models.PhanBoSach

@{
    ViewData["Title"] = "EditPBSach";
}

<h2>EditPBSach</h2>

<h4>PhanBoSach</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditPBSach">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" value="@{if(Model.Id.Contains("*")){ Model.Id.Replace("*", "/"); } else { @Model.Id; } }"/>
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MaSach" class="control-label"></label>
                <input asp-for="MaSach" class="form-control" />
                <span asp-validation-for="MaSach" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MaChiNhanh" class="control-label"></label>
                <input asp-for="MaChiNhanh" class="form-control" />
                <span asp-validation-for="MaChiNhanh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SoLuongGoc" class="control-label"></label>
                <input asp-for="SoLuongGoc" class="form-control" />
                <span asp-validation-for="SoLuongGoc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SoLuongCon" class="control-label"></label>
                <input asp-for="SoLuongCon" class="form-control" />
                <span asp-validation-for="SoLuongCon" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="KiemTra" /> @Html.DisplayNameFor(model => model.KiemTra)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Source/RavenDB_Embedded/Views/QuanLy/EditSach.cshtml
@model RavenDB_Embedded.Models.Sach

@{
    ViewData["Title"] = "EditSach";
}

<h2>EditSach</h2>

<h4>Sach</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditSach">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" value="@{if (Model.Id.Contains("*")) { Model.Id.Replace("*", "/"); } else { @Model.Id; } }"/>
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MaSach" class="control-label"></label>
                <input asp-for="MaSach" class="form-control" />
                <span asp-validation-for="MaSach" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TenSach" class="control-label"></label>
                <input asp-for="TenSach" class="form-control" />
                <span asp-validation-for="TenSach" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Hinh" class="control-label"></label>
                <input asp-for="Hinh" class="form-control" />
                <span asp-validation-for="Hinh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TenTacGia" class="control-label"></label>
                <input asp-for="TenTacGia" class="form-control" />
                <span asp-validation-for="TenTacGia" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NhaXuatBan" class="control-label"></label>
                <input asp-for="NhaXuatBan" class="form-control" />
                <span asp-validation-for="NhaXuatBan" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NamXuatBan" class="control-label"></label>
                <input asp-for="NamXuatBan" class="form-control" />
                <span asp-validation-for="NamXuatBan" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LoiGioiThieu" class="control-label"></label>
                <input asp-for="LoiGioiThieu" class="form-control" />
                <span asp-validation-for="LoiGioiThieu" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rating" class="control-label"></label>
                <input asp-for="Rating" class="form-control" />
                <span asp-validation-for="Rating" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ChiNhanh" class="control-label"></label>
                <input asp-for="ChiNhanh" class="form-control" />
                <span asp-validation-for="ChiNhanh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Source/RavenDB_Embedded/Views/QuanLy/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<br />
<h2>Các chức năng của Quản lý</h2>

<div class="row">
    <div class="col-md-6">
        <a href="@Url.Action("ListYeuCau","QuanLy")">Thống kê yêu cầu mua sách</a><br />
        <a href="@Url.Action("ListSach","QuanLy")">Quản lý sách</a><br />
        <a href="@Url.Action("ListPhanBo","QuanLy")">Phân bổ sách</a><br />
        <a href="@Url.Action("ListDocGia","QuanLy")">Quản lý độc giả</a><br />
    </div>
</div>

<style>
    a {
        font-size: 30px;
    }
</style>

Source/RavenDB_Embedded/Views/QuanLy/ListDocGia.cshtml
@model IEnumerable<RavenDB_Embedded.Models.DocGia>

@{
    ViewData["Title"] = "ListDocGia";
}

<h2>ListDocGia</h2>

<p>
    <a asp-action="AddDocGia">Thêm độc giả mới</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MaLoaiDG)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MaDG)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TenDG)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SoDienThoai)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MaLoaiDG)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MaDG)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TenDG)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SoDienThoai)
            </td>
            <td>
                <a asp-action="EditDocGia" asp-route-id="@item.Id.Replace("/","*")">Edit</a>
            </td>
            <td></td>
            <td>
                <a asp-action="DeleteDocGia" asp-route-id="@item.Id.Replace("/","*")">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Source/RavenDB_Embedded/Views/QuanLy/ListPhanBo.cshtml
@model IEnumerable<RavenDB_Embedded.Models.PhanBoSach>

@{
    ViewData["Title"] = "ListPhanBo";
}

<h2>Danh sách phân bố sách tại các chi nhánh</h2>

<p>
    <a asp-action="CreatePBSach">Phân bổ sách mới</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MaSach)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MaChiNhanh)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SoLuongGoc)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SoLuongCon)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.KiemTra)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MaSach)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MaChiNhanh)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SoLuongGoc)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SoLuongCon)
            </td>
            <td>
                <a asp-action="EditPBSach" asp-route-id="@item.Id.Replace("/","*")">Edit</a>
            </td>
            <td></td>
            <td>
                <a asp-action="DeletePBSach" asp-route-id="@item.Id.Replace("/","*")">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Source/RavenDB_Embedded/Views/QuanLy/ListYeuCau.cshtml
@model IEnumerable<RavenDB_Embedded.Models.YeuCauMuaSach>

@{
    ViewData["Title"] = "ListYeuCau";
}

<h2>Yêu cầu mua thêm sách</h2>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MaDG)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TenSach)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MaCN)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SoLuong)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MaDG)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TenSach)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MaCN)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SoLuong)
            </td>
            <td>
                <a asp-action="DeleteYC" asp-controller="QuanLy" asp-route-id="@item.Id.Replace("/","*")">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>
<a asp-action="ListPhanBo"><input type="submit" value="Phân bổ sách" class="btn btn-primary" /></a>